### ISSUE TITLE
缺少“睛彩青少”Logo

### ISSUE THREAD

**Issue by cnmake** [kakaxi-1/IPTV#2]
睛彩羽毛球频道于4月25日变更为晴彩青少频道
没找到高清图片，也就是下面的文字变一下。
![image](https://github.com/user-attachments/assets/5b07a928-eb7d-4141-a106-90ed5d723a77)
![image](https://github.com/user-attachments/assets/2a2307c0-6488-45ac-bfe2-c71da73ee5fc)

**Comment by nourakhy** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)

**Comment by kakaxi-1** [comment]
解决

**Comment by cnmake** [comment]
> 解决

用上了谢谢。
就是渐变的颜色浅了一点儿，可以再优化。
![image](https://github.com/user-attachments/assets/8389346a-2a2b-4a3f-b41d-c28d98e5d88b)

**Comment by kakaxi-1** [comment]
> > 解决
> 
> 
> 
> 用上了谢谢。
> 
> 就是渐变的颜色浅了一点儿，可以再优化。
> 
> ![image](https://github.com/user-attachments/assets/8389346a-2a2b-4a3f-b41d-c28d98e5d88b)

Png透明的，放播放器上没啥区别
